import { EXPERT_PERSONAS, ExpertPersona } from "./personas";
import { MODELS, getClient } from "./models";

export interface EnsembleResult {
  geminiAnswer: string;
  groqAnswer: string;
  agreement: number;
  disagreements: string[];
  mergedInsights: string[];
  confidenceBoost: number;
}

export async function ensembleCheck(
  query: string,
  geminiAnswer: string,
  persona: ExpertPersona,
  groqConfig: { useGroq: boolean; groqApiKey?: string; groqModel?: string },
  apiKey?: string
): Promise<EnsembleResult | null> {
  if (!groqConfig.useGroq || !groqConfig.groqApiKey) {
    return null;
  }

  const systemInstruction = EXPERT_PERSONAS[persona] || EXPERT_PERSONAS.conversationalist;
  let groqAnswer = "";

  // 1. Call Groq via fetch
  try {
    const url = "https://api.groq.com/openai/v1/chat/completions";
    const model = groqConfig.groqModel || MODELS.GROQ_DEFAULT;
    const response = await fetch(url, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${groqConfig.groqApiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model,
        temperature: 0.5,
        max_tokens: 1500,
        messages: [
          { role: "system", content: systemInstruction },
          { role: "user", content: query }
        ]
      })
    });

    if (response.ok) {
      const data = await response.json();
      groqAnswer = data.choices?.[0]?.message?.content || "";
    } else {
      console.error(`Groq API returned status ${response.status} in ensemble check`);
      return null;
    }
  } catch (err) {
    console.error("Groq call failed in ensemble check:", err);
    return null;
  }

  if (!groqAnswer) {
    return null;
  }

  // 2. Call Gemini to compare the two answers
  const client = getClient(apiKey);
  const compareInstruction = `You are a cross-model evaluation engine. Compare two answers to the same user query generated by different AI models.
Evaluate:
1. Do they agree on core facts?
2. What are the specific disagreements/contradictions (if any)?
3. What unique insights does Model B (Groq) provide that Model A (Gemini) missed?
4. Calculate a percentage agreement (0-100) representing how consistent their core conclusions are.

Return a JSON object conforming exactly to this schema:
{
  "agreement": <integer 0 to 100>,
  "disagreements": ["<disagreement 1>", "<disagreement 2>"],
  "mergedInsights": ["<unique insight from Groq 1>", ...]
}`;

  const contents = `User Query: "${query}"\n\n--- MODEL A (Gemini) ANSWER ---\n${geminiAnswer}\n\n--- MODEL B (Groq) ANSWER ---\n${groqAnswer}`;

  try {
    const response = await client.models.generateContent({
      model: MODELS.PRIMARY,
      contents,
      config: {
        systemInstruction: compareInstruction,
        maxOutputTokens: 500,
        responseMimeType: "application/json",
        responseSchema: {
          type: "object",
          properties: {
            agreement: { type: "number" },
            disagreements: { type: "array", items: { type: "string" } },
            mergedInsights: { type: "array", items: { type: "string" } }
          },
          required: ["agreement", "disagreements", "mergedInsights"]
        } as any
      }
    });

    const parsed = JSON.parse(response.text || "{}");
    const agreement = parsed.agreement ?? 100;
    
    // Calculate boost: positive if agreement is high, negative if they conflict
    const confidenceBoost = Math.round((agreement - 70) * 0.3);

    return {
      geminiAnswer,
      groqAnswer,
      agreement,
      disagreements: Array.isArray(parsed.disagreements) ? parsed.disagreements : [],
      mergedInsights: Array.isArray(parsed.mergedInsights) ? parsed.mergedInsights : [],
      confidenceBoost
    };
  } catch (err) {
    console.error("Gemini model comparison in ensemble check failed:", err);
    return {
      geminiAnswer,
      groqAnswer,
      agreement: 80,
      disagreements: [],
      mergedInsights: [],
      confidenceBoost: 3
    };
  }
}
